export const initialForm = {
  patientValue: '',
  patientName: '',
  birthday: {},
  avatar:'',
  birthdayStr: null,
  address:'',
  idNo: 0,
  phone: 0,
  gender: 1,
  jobId: null,
  nationalityId: 1000179,
  ethnicityId: 1000000,
  priority: false,
  appointment: false,
  countryId: 1000179,
  provinceId: null,
  districtId: null,
  zoneId: null,
  detailAddress: '',
  guardianName: '',
  guardianPhone: 0,
  guardianIdNo: 0,
  notCopayment: '',
  id: null,
  receptionId: null
};
