export const convertService = (service, userApp, patient, department) => ({
	option: true,
	patientHistoryId: patient.id,
	serviceId: service.id,
	roomId: service.roomId,
	servicePurposeId: service.servicePurposeId,
	notCounted: service.notCounted,
	serviceUsed: false,
	quantity: 1,
	serviceInHospital: true,
	diagnostic: null,
	fromDoctorId: null,
	patientRequest: false,
	mainUser1Id: null,
	docDate: new Date(),
	actDate: new Date(),
	fromDepartmentId: userApp.department.value,
	deferredPayment: service.serviceType === 10 ? !!department.deferredPayment : false,
	createdFromRecordId: patient.id,
	createdFromServiceType: 200,
	description: '',
	specimens: '',
});