import { CheckAll, CheckOne, Actions, RenderDate, RenderNumber, RenderBoolean, RenderOneOf, RenderData, CheckAllHeader } from './components';

export const columns = [
	{ key: 'checkAll', value: '', title: 'Tất cả', component: CheckAll, sortFunc: '', width: 90, resize: false, fixed: 'left', titleCom: CheckAllHeader },
	{ key: 'checked', value: '', title: '', component: CheckOne, sortFunc: '', width: 40, fixed: 'left' },
	{ key: 'no', value: 'no', title: 'STT', component: '', sortFunc: '', width: 50, fixed: 'left' },
	{ key: 'value', value: 'value', title: 'Mã DV', component: RenderData, sortFunc: () => {}, width: 100, fixed: 'left', resize: false },
	{ key: 'serviceName', value: 'serviceName', title: 'Tên DV', component: RenderData, sortFunc: () => {}, width: 200, fixed: '', resize: true },
	{ key: 'roomId', value: 'roomId', title: 'Phòng', component: RenderOneOf, sortFunc: null, width: 200, fixed: '', resize: true, oneOf: 'rooms' },
	{ key: 'quantity', value: 'quantity', title: 'SL', component: RenderData, sortFunc: '', width: 30, fixed: '', resize: true },
	{ key: 'unit', value: 'uomId', title: 'DVT', component: RenderOneOf, sortFunc: '', width: 40, fixed: '', resize: true, oneOf: 'uom' },
	{ key: 'result', value: 'result', title: 'Kết quả', component: RenderData, sortFunc: '', width: 150, fixed: '', resize: true },
	{ key: 'conclusion', value: 'conclusion', title: 'Kết luận', component: RenderData, sortFunc: '', width: 150, fixed: '', resize: true },
	{ key: 'actDate', value: 'actDate', title: 'Ngày TH', component: RenderDate, sortFunc: () => {}, width: 150, fixed: '', resize: true },
	{ key: 'status', value: 'status', title: 'Trạng thái', component: RenderOneOf, sortFunc: () => {}, width: 120, fixed: '', resize: true, oneOf: 'status' },
	{ key: 'fromDoctorId', value: 'fromDoctorId', title: 'BS chỉ định', component: RenderOneOf, sortFunc: '', width: 150, fixed: '', oneOf: 'users', resize: true },
	{ key: 'paid', value: 'paid', title: 'Đã TT', component: RenderBoolean, sortFunc: '', width: 40, fixed: '', resize: true },
	{ key: 'deferredPayment', value: 'deferredPayment', title: 'Thanh toán sau', component: RenderBoolean, sortFunc: '', width: 120, fixed: '', resize: true },
	{ key: 'serviceUsed', value: 'serviceUsed', title: 'Tự túc', component: RenderBoolean, sortFunc: '', width: 60, fixed: '', resize: true },
	{ key: 'notCounted', value: 'notCounted', title: 'Không tính tiền', component: RenderBoolean, sortFunc: '', width: 60, fixed: '', resize: true },
	{ key: 'servicePurposeId', value: 'servicePurposeId', title: 'DKTTTT35', component: RenderOneOf, sortFunc: '', width: 150, fixed: '', resize: true, oneOf: 'servicePurposes' },
	{ key: 'specimens', value: 'specimens', title: 'Bệnh phẩm', component: '', sortFunc: '', width: 200, fixed: '', resize: true },
	{ key: 'biopsyLocationId', value: 'biopsyLocationId', title: 'Vị trí sinh thiết', component: RenderOneOf, sortFunc: '', width: 200, fixed: '', oneOf: 'biopsyLocations', resize: true },
	{ key: 'specimenProperty', value: 'specimenProperty', title: 'Tính chất bệnh phẩm', component: RenderOneOf, sortFunc: '', width: 200, fixed: '', resize: true, oneOf: 'specimenProperty' },
	{ key: 'dyeMethodId', value: 'dyeMethodId', title: 'Phương pháp nhuộm', component: RenderOneOf, sortFunc: '', width: 200, fixed: '', oneOf: 'dyeMethods', resize: true },
	{ key: 'description', value: 'description', title: 'Mô tả', component: RenderData, sortFunc: '', width: 150, fixed: '', resize: true },
	{ key: 'diagnostic', value: 'diagnostic', title: 'Chẩn đoán', component: RenderData, sortFunc: '', width: 150, fixed: '', resize: true },
	{ key: 'patientRequest', value: 'patientRequest', title: 'NB yêu cầu', component: RenderBoolean, sortFunc: '', width: 90, fixed: '', resize: true },
	{ key: 'fromDoctorId2', value: 'fromDoctorId', title: 'Người kê', component: RenderOneOf, sortFunc: '', width: 150, fixed: '', oneOf: 'users', resize: true },
	{ key: 'insurancePaid', value: 'insurancePaid', title: 'Đã thanh toán BH', component: RenderBoolean, sortFunc: '', width: 120, fixed: '', resize: true },
	{ key: 'servicePaid', value: 'servicePaid', title: 'Đã thanh toán DV', component: RenderBoolean, sortFunc: '', width: 120, fixed: '', resize: true },
	{ key: 'serviceUnitPrice', value: 'serviceUnitPrice', title: 'Giá DV', component: RenderNumber, sortFunc: '', width: 90, fixed: '', resize: true },
	{ key: 'insuranceUnitPrice', value: 'insuranceUnitPrice', title: 'Giá BH', component: RenderNumber, sortFunc: '', width: 90, fixed: '', resize: true },
	{ key: 'differenceUnitPrice', value: 'differenceUnitPrice', title: 'Giá Chênh', component: RenderNumber, sortFunc: '', width: 90, fixed: '', resize: true },
	{ key: 'docDate', value: 'docDate', title: 'Ngày kê', component: RenderDate, sortFunc: '', width: 150, fixed: '', resize: true },
	{ key: 'mainUser1Id', value: 'mainUser1Id', title: 'BS khám', component: RenderOneOf, sortFunc: '', width: 150, fixed: '', oneOf: 'users', resize: true },
	{ key: 'mainUser1Id-2', value: 'mainUser1Id', title: 'Người TH chính', component: RenderOneOf, sortFunc: '', width: 150, fixed: '', oneOf: 'users', resize: true },
	{ key: 'subUser1Id', value: 'subUser1Id', title: 'Người TH phụ', component: RenderOneOf, sortFunc: '', width: 150, fixed: '', oneOf: 'users', resize: true },
	{ key: 'resultDate', value: 'resultDate', title: 'Thời gian có kết quả', component: RenderDate, sortFunc: '', width: 200, fixed: '', resize: true },
	{ key: 'acceptedDate', value: 'acceptedDate', title: 'Thời gian tiếp nhận', component: RenderDate, sortFunc: '', width: 200, fixed: '', resize: true },
	{ key: 'fromDepartmentId', value: 'fromDepartmentId', title: 'Khoa chỉ định', component: RenderOneOf, sortFunc: '', width: 200, fixed: '', oneOf: 'departments', resize: true },
	{ key: 'action', value: '', title: 'Thao tác', component: Actions, sortFunc: '', width: 60, fixed: '' },
];
